---
outline: deep
---

# 线程方法

## run start

### run

称为线程体，包含了要执行的这个线程的内容，方法运行结束，此线程随即终止。直接调用 run 是在主线程中执行了 run，没有启动新的线程，需要顺序执行。

::: warning run() 方法中的异常不能抛出，只能 try/catch
因为父类中没有抛出任何异常，子类不能比父类抛出更多的异常
**异常不能跨线程传播回 main() 中**，因此必须在本地进行处理
:::

### start

使用 start 是启动新的线程，此线程处于就绪（可运行）状态，通过新的线程间接执行 run 中的代码。

## join

public final void join()：等待这个线程结束，此方法会阻塞主线程，和FutureTask的 get()方法类似。

```java
public final synchronized void join(long millis) throws InterruptedException {
    // 调用者线程进入 thread 的 waitSet 等待, 直到当前线程运行结束
    while (isAlive()) {
        wait(0);
    }
}
```

- join 方法是被 synchronized 修饰的，本质上是一个对象锁，其内部的 wait 方法调用也是释放锁的，但是**释放的是当前的线程对象锁，而不是外面的锁**
- 当调用某个线程（t1）的 join 方法后，该线程（t1）抢占到 CPU 资源，就不再释放，直到线程执行完毕


::: tip 线程同步
- join 实现线程同步，因为会阻塞等待另一个线程的结束，才能继续向下运行
  - 需要外部共享变量，不符合面向对象封装的思想
  - 必须等待线程结束，不能配合线程池使用
- Future 实现（同步）：get() 方法阻塞等待执行结果
  - main 线程接收结果
  - get() 方法是让调用线程同步等待
:::

### 示范

```java
public class Test {
    static int r = 0;
    public static void main(String[] args) throws InterruptedException {
        test1();
    }
    private static void test1() throws InterruptedException {
        Thread t1 = new Thread(() -> {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            r = 10;
        });
        t1.start();
        t1.join();//不等待线程执行结束，输出的10
        System.out.println(r);
    }
}
```

## interrupt 

### isInterrupted()

::: tip public boolean isInterrupted()
判断当前线程是否被中断（通过检查中断标志位）。
:::

#### 示范

```java
public static void main(String[] args) {

    Thread t1 = new Thread(() -> {

        while (true) {

            /**
             * public boolean isInterrupted()
             * 实例方法
             * 判断当前线程是否被中断（通过检查中断标志位）
             */
            if (Thread.currentThread().isInterrupted()) {
                System.out.println("程序被打断"+Thread.currentThread().isInterrupted());
                break;
            }
            System.out.println("t1 --------hello interrupt api");
        }


    }, "t1");

    t1.start();
}
```
###  interrupt()


::: tip public void interrupt()
Unless the current thread is interrupting itself, which is always permitted, the checkAccess method of this thread is invoked, which may cause a SecurityException to be thrown.

If this thread is blocked in an invocation of the `wait(), wait(long), or wait(long, int)` methods of the Object class, or of the `join(), join(long), join(long, int), sleep(long), or sleep(long, int)`, methods of this class, then its interrupt status will be `cleared` and it will `receive an InterruptedException`.

If this thread is blocked in an I/O operation upon an InterruptibleChannel then the channel will be closed, the thread's interrupt status will be set, and the thread will receive a java.nio.channels.ClosedByInterruptException.

If this thread is blocked in a java.nio.channels.Selector then the thread's interrupt status will be set and it will return immediately from the selection operation, possibly with a non-zero value, just as if the selector's wakeup method were invoked.

If none of the previous conditions hold then this thread's interrupt status will be set.

Interrupting a thread that is not alive need not have any effect.

:::

上面部分官方注释可知道 `如果这个线程在Object类的wait()、wait(long)或wait(long, int)方法的调用中被阻塞，或者在该类的join()、join(long)、join(long, int)、sleep(long)或sleep(long, int)方法的调用中被阻塞，那么它的中断状态将被清除，它将接收一个InterruptedException异常。`

#### 示范
::: code-group

```java [打断wait()方法]
  private static void test1() throws InterruptedException {
    Object o = new Object();
    Thread t1 = new Thread(()->{
      try {
        // sleep(5);
        synchronized (o){
          o.wait();
        }
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    }, "t1");
    
    t1.start();
    sleep(0.5);
    t1.interrupt();
    log.debug(" 打断状态: {}", t1.isInterrupted());
  }
```

```log [控制台输出]
Exception in thread "t1" java.lang.RuntimeException: java.lang.InterruptedException
	at com.kwfruit.ending.InterruptTest.lambda$test1$0(InterruptTest.java:33)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at com.kwfruit.ending.InterruptTest.lambda$test1$0(InterruptTest.java:29)
	... 1 more
09:49:57.396 [main] DEBUG com.kwfruit.ending.InterruptTest -  打断状态: false
```
:::


### interrupted()
::: tip public static boolean interrupted()
返回当前线程的中断状态，测试当前线程是否已被中断，将当前线程的中断状态清零并重新设置为false，**清除线程的中断状态**
:::
#### 示范

```java
public class InterruptDemo4 {
    
    public static void main(String[] args) {
        //测试当前线程是否被中断（检查中断标志）, 返回一个boolean并清除中断状态，
        //第二次再调用时中断状态已经被清除，将返回一个false。

        System.out.println(Thread.currentThread().getName()+"\t"+Thread.interrupted());//false
        System.out.println(Thread.currentThread().getName()+"\t"+Thread.interrupted());//false
        System.out.println("--1");
        Thread.currentThread().interrupt(); //中断标志位设置为true
        System.out.println("--2");
        System.out.println(Thread.currentThread().getName()+"\t"+Thread.interrupted());//true
        System.out.println(Thread.currentThread().getName()+"\t"+Thread.interrupted());//false
        
        Thread.interrupted();//静态方法
        Thread.currentThread().isInterrupted();//实例方法
    }

}
```


